# CMake generated Testfile for 
# Source directory: D:/GitHub/bariver996/libzmq/unittests
# Build directory: D:/GitHub/bariver996/libzmq/builds/cmake/unittests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(unittest_ypipe "D:/GitHub/bariver996/libzmq/builds/cmake/bin/Debug/unittest_ypipe.exe")
  set_tests_properties(unittest_ypipe PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;47;add_test;D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(unittest_ypipe "D:/GitHub/bariver996/libzmq/builds/cmake/bin/Release/unittest_ypipe.exe")
  set_tests_properties(unittest_ypipe PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;47;add_test;D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(unittest_ypipe "D:/GitHub/bariver996/libzmq/builds/cmake/bin/MinSizeRel/unittest_ypipe.exe")
  set_tests_properties(unittest_ypipe PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;47;add_test;D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(unittest_ypipe "D:/GitHub/bariver996/libzmq/builds/cmake/bin/RelWithDebInfo/unittest_ypipe.exe")
  set_tests_properties(unittest_ypipe PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;47;add_test;D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;0;")
else()
  add_test(unittest_ypipe NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(unittest_poller "D:/GitHub/bariver996/libzmq/builds/cmake/bin/Debug/unittest_poller.exe")
  set_tests_properties(unittest_poller PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;47;add_test;D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(unittest_poller "D:/GitHub/bariver996/libzmq/builds/cmake/bin/Release/unittest_poller.exe")
  set_tests_properties(unittest_poller PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;47;add_test;D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(unittest_poller "D:/GitHub/bariver996/libzmq/builds/cmake/bin/MinSizeRel/unittest_poller.exe")
  set_tests_properties(unittest_poller PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;47;add_test;D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(unittest_poller "D:/GitHub/bariver996/libzmq/builds/cmake/bin/RelWithDebInfo/unittest_poller.exe")
  set_tests_properties(unittest_poller PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;47;add_test;D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;0;")
else()
  add_test(unittest_poller NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(unittest_mtrie "D:/GitHub/bariver996/libzmq/builds/cmake/bin/Debug/unittest_mtrie.exe")
  set_tests_properties(unittest_mtrie PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;47;add_test;D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(unittest_mtrie "D:/GitHub/bariver996/libzmq/builds/cmake/bin/Release/unittest_mtrie.exe")
  set_tests_properties(unittest_mtrie PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;47;add_test;D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(unittest_mtrie "D:/GitHub/bariver996/libzmq/builds/cmake/bin/MinSizeRel/unittest_mtrie.exe")
  set_tests_properties(unittest_mtrie PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;47;add_test;D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(unittest_mtrie "D:/GitHub/bariver996/libzmq/builds/cmake/bin/RelWithDebInfo/unittest_mtrie.exe")
  set_tests_properties(unittest_mtrie PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;47;add_test;D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;0;")
else()
  add_test(unittest_mtrie NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(unittest_ip_resolver "D:/GitHub/bariver996/libzmq/builds/cmake/bin/Debug/unittest_ip_resolver.exe")
  set_tests_properties(unittest_ip_resolver PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;47;add_test;D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(unittest_ip_resolver "D:/GitHub/bariver996/libzmq/builds/cmake/bin/Release/unittest_ip_resolver.exe")
  set_tests_properties(unittest_ip_resolver PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;47;add_test;D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(unittest_ip_resolver "D:/GitHub/bariver996/libzmq/builds/cmake/bin/MinSizeRel/unittest_ip_resolver.exe")
  set_tests_properties(unittest_ip_resolver PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;47;add_test;D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(unittest_ip_resolver "D:/GitHub/bariver996/libzmq/builds/cmake/bin/RelWithDebInfo/unittest_ip_resolver.exe")
  set_tests_properties(unittest_ip_resolver PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;47;add_test;D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;0;")
else()
  add_test(unittest_ip_resolver NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(unittest_udp_address "D:/GitHub/bariver996/libzmq/builds/cmake/bin/Debug/unittest_udp_address.exe")
  set_tests_properties(unittest_udp_address PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;47;add_test;D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(unittest_udp_address "D:/GitHub/bariver996/libzmq/builds/cmake/bin/Release/unittest_udp_address.exe")
  set_tests_properties(unittest_udp_address PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;47;add_test;D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(unittest_udp_address "D:/GitHub/bariver996/libzmq/builds/cmake/bin/MinSizeRel/unittest_udp_address.exe")
  set_tests_properties(unittest_udp_address PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;47;add_test;D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(unittest_udp_address "D:/GitHub/bariver996/libzmq/builds/cmake/bin/RelWithDebInfo/unittest_udp_address.exe")
  set_tests_properties(unittest_udp_address PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;47;add_test;D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;0;")
else()
  add_test(unittest_udp_address NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(unittest_radix_tree "D:/GitHub/bariver996/libzmq/builds/cmake/bin/Debug/unittest_radix_tree.exe")
  set_tests_properties(unittest_radix_tree PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;47;add_test;D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(unittest_radix_tree "D:/GitHub/bariver996/libzmq/builds/cmake/bin/Release/unittest_radix_tree.exe")
  set_tests_properties(unittest_radix_tree PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;47;add_test;D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(unittest_radix_tree "D:/GitHub/bariver996/libzmq/builds/cmake/bin/MinSizeRel/unittest_radix_tree.exe")
  set_tests_properties(unittest_radix_tree PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;47;add_test;D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(unittest_radix_tree "D:/GitHub/bariver996/libzmq/builds/cmake/bin/RelWithDebInfo/unittest_radix_tree.exe")
  set_tests_properties(unittest_radix_tree PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;47;add_test;D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;0;")
else()
  add_test(unittest_radix_tree NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(unittest_curve_encoding "D:/GitHub/bariver996/libzmq/builds/cmake/bin/Debug/unittest_curve_encoding.exe")
  set_tests_properties(unittest_curve_encoding PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;47;add_test;D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(unittest_curve_encoding "D:/GitHub/bariver996/libzmq/builds/cmake/bin/Release/unittest_curve_encoding.exe")
  set_tests_properties(unittest_curve_encoding PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;47;add_test;D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(unittest_curve_encoding "D:/GitHub/bariver996/libzmq/builds/cmake/bin/MinSizeRel/unittest_curve_encoding.exe")
  set_tests_properties(unittest_curve_encoding PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;47;add_test;D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(unittest_curve_encoding "D:/GitHub/bariver996/libzmq/builds/cmake/bin/RelWithDebInfo/unittest_curve_encoding.exe")
  set_tests_properties(unittest_curve_encoding PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;47;add_test;D:/GitHub/bariver996/libzmq/unittests/CMakeLists.txt;0;")
else()
  add_test(unittest_curve_encoding NOT_AVAILABLE)
endif()
